name: CI
on:
  push:
    branches:
      - '**'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - run: npm install

    - name: Run tests for v1
      run: xvfb-run -a npm run test:v1
    
    - name: Run tests
      run: xvfb-run -a npm test
    
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/v')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}